version: "3"

networks:
  frontend:
  backend:

volumes:
  redisdata:
  pgdata:
  pgvectordata:

services:
  kakaosearchbot:
    restart: always
    build: ./kakaosearchbot
    ports:
      - "8400:8000" # django
    volumes:
      - ./web:/app

    networks:
      - backend
      - frontend
    env_file: .env
    command: ./bootup.sh

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8480:80"
    networks:
      - frontend
      - backend
    depends_on:
      - kakaosearchbot
    volumes:
      - ./nginx/sites-enabled/nginx.conf:/etc/nginx/nginx.conf
